_base_:
  - cfgs/train/dataset/base_dataset.yaml
  - cfgs/train/train_base.yaml
  - cfgs/train/tuning_base.yaml

train:
  train_TE: True
  save_step: 10000
  train_steps: 150000
  max_grad_norm: 1.0
  scale_lr: False

  # resume：从80000步继续，不重置步数
  resume:
    start_step: 80000
    ckpt_path:
      unet:
        - "exps/2026-04-12-22-46-03/ckpts/unet-80000.safetensors"
      TE:
        - "exps/2026-04-12-22-46-03/ckpts/text_encoder-80000.safetensors"
      words: []

  scheduler:
    name: "constant_with_warmup"
    num_warmup_steps: 500
    num_training_steps: ${train.train_steps}
    scheduler_kwargs: {}

model:
  pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
  tokenizer_repeats: 1
  ema_unet: 1
  ema_text_encoder: 1

  use_morphology_prior: True
  geom_param_indices: [5, 6, 7, 8] # 这里非常重要！必须填 R, E1, E2, Sersic 在你 22维参数里的准确 Index
  latent_size: 24

  text_encoder:
    _target_: hcpdiff.models.textencoder_catalog.CatalogTextEncoder
    feature_dim: 22
    hidden_dim: 1024
    output_dim: 768
    num_tokens: 22
    norm_stats_path: "/nfsdata/share/ljc/DESI_data/data_catalog_weighted-mass_emline-z-by_readeID/normalization_stats_v3.csv"

unet:
  - lr: 1e-4
    layers:
      - "conv_in"      # 新加的第5通道权重需要快速学习

  - lr: 1e-6           # 其余层极低学习率，保护现有收敛
    layers:
      - "time_embedding"
      - "down_blocks"
      - "mid_block"
      - "up_blocks"
      - "conv_norm_out"
      - "conv_out"

text_encoder:
  # adagn_projector输出×20后梯度也×20，用3e-5防止过度更新
  # 其余TE参数跟随降档
  - lr: 1e-6
    layers:
      - ""

data_cfg:
  batch_size: 16
  img_root: "/nfsdata/share/ljc/DESI_data/data_catalog_weighted-mass_emline-z-by_readeID/filtered_data"
  catalog_file: "/nfsdata/share/ljc/DESI_data/data_catalog_weighted-mass_emline-z-by_readeID/labeled_catalog_cleaned_v3.csv"
  target_area: 192*192

data:
  dataset1:
    batch_size: ${data_cfg.batch_size}
    cache_latents: True
    cache_path: "/nfsdata/share/ljc/DESI_data/data_catalog_weighted-mass_emline-z-by_readeID/latent_cache_v3/"

    source:
      data_source1:
        _target_: hcpdiff.data.source.text2img_catalog.Text2ImageCatalogSource
        img_root: ${data_cfg.img_root}
        catalog_file: ${data_cfg.catalog_file}
        text_transforms:
          _target_: torchvision.transforms.Compose
          transforms:
            - _target_: hcpdiff.utils.caption_tools.TemplateFill
              word_names: {}

    bucket:
      _target_: hcpdiff.data.bucket.SizeBucket.from_files
      target_area: ${data_cfg.target_area}
      num_bucket: 1